import React from 'react'

export default function StatisticsHome() {
  return (
    <div className='p-10'>
      <h1 className='text-3xl'>Statistics</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi fugit dolorem dicta! Similique incidunt harum numquam corporis explicabo dolore culpa ad sed sint exercitationem aliquam facere et iste delectus, libero vitae molestiae cum fuga, consectetur saepe ipsam aliquid ea. Illo consequuntur in eveniet delectus itaque quam quia ea eaque. Eaque corporis vitae sequi dignissimos libero soluta sapiente illum dolores atque ducimus rem odit, fuga recusandae ullam! Sint quisquam obcaecati, suscipit laborum, ratione natus iure deserunt repudiandae totam molestiae repellat tempore harum dolor modi amet. Minus magnam dignissimos fugiat assumenda amet ea, perferendis quibusdam aperiam dolorum earum ipsa sit. Tempore, aut.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe hic pariatur vel nihil aspernatur, harum blanditiis nesciunt ducimus quasi quae illum eum, in distinctio cupiditate quisquam ab id asperiores incidunt nobis nisi esse delectus eos! At iure maiores perferendis cum laboriosam officia nemo molestias labore mollitia consectetur repellendus, laudantium dicta! Nulla quia consequatur quisquam aliquid quo nisi beatae quae provident tenetur minus explicabo omnis odit tempore eaque nesciunt, obcaecati qui temporibus voluptates ab quam consectetur similique accusamus facilis et! Sequi, molestiae dolor. Corrupti, incidunt laboriosam dolorem quam reiciendis aperiam, eveniet blanditiis accusantium quos facilis necessitatibus vero aliquid similique modi omnis ex quod optio facere, laudantium expedita eos. Veritatis debitis pariatur, voluptatibus quia deleniti delectus exercitationem recusandae eius ad corrupti excepturi tenetur libero eligendi alias! Veniam ullam nam laudantium magni ad, doloremque accusamus quisquam quibusdam corporis dolore expedita iste nisi animi. Sequi repellendus facilis eveniet, facere in tempora odio eligendi deleniti!</p>
    </div>
  )
}